<br>
<br>
<br>

<p style = "text-indent : 100px"> <?php echo $this->status; ?> </p>

<br>

<a style = 'margin-left : 100px;' href = "<?php echo $this->url('student',
    array('action' => 'index')); ?>"><input type = "button" value = "Home Page"></a>

<a style = 'margin-left : 50px;' href = " <?php echo $this->url('student',
    array('action' => 'add')); ?> "> <input type = "button" value = "Add Student"></a>


